### ISSUE TITLE
Move to Multiformats?

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/ruby-multihash#1]
Hey Kyle!

Thanks so much for this. As you may know, we recently created the [Multiformats](//github.com/multiformats) organization to be a home for all of the multiformats - multiaddr, multihash, etc. Would you be interested in moving this repository to that organization? You would still have admin rights on the repository, but it would be a part of a wider organization. This would mean more relevant eyes on it (most likely) and better cross-repository issue tracking. We'd also add a line mentioning you as the original author, and of course your commits would stay the same. 

Of course, keeping it on your profile is also cool; we'll still link to this from the main multihash repository at github.com/multiformats/multihash.

Thanks for taking the time to read this. 👍 

Tracking issue, here: https://github.com/multiformats/multiformats/issues/4.

**Comment by kyledrake** [comment]
That sounds good to me. What is the next step here?

**Comment by RichardLitt** [comment]
Added you as a member of the org. You can transfer it over, now, and I'll re-add you as an admin for this repo. Sound good?

**Comment by kyledrake** [comment]
I'm not seeing myself on the list, so I can't transfer it over (by transfer do you mean fork, or init as a new repo?)

**Comment by RichardLitt** [comment]
Hmm, weird. I mean move the ownership over; see https://github.com/neocities/ruby-multihash/settings, and click "Transfer Ownership".

<img width="757" alt="screen shot 2016-09-14 at 2 52 15 pm" src="https://cloud.githubusercontent.com/assets/910753/18525529/d940bb38-7a8a-11e6-9dfd-06e5416948b3.png">

**Comment by kyledrake** [comment]
"You don’t have admin rights to multiformats"

**Comment by RichardLitt** [comment]
Weird; I've added you twice to the Multiformats organization. Are you getting my invites in your inbox?

**Comment by kyledrake** [comment]
Nope, it was in a really weird place on their site! Okay it should work now, standby

**Comment by kyledrake** [comment]
Done.

**Comment by RichardLitt** [comment]
Nice! I added you as an admin. What's next is for me to standardize the Readme, and link this from multiformats/multiformats.

Thanks Kyle!
